// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.12.4
// source: api/proto/scraper.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScraperService_FetchArticle_FullMethodName  = "/scraper.ScraperService/FetchArticle"
	ScraperService_FetchArticles_FullMethodName = "/scraper.ScraperService/FetchArticles"
	ScraperService_FetchRaw_FullMethodName      = "/scraper.ScraperService/FetchRaw"
	ScraperService_HealthCheck_FullMethodName   = "/scraper.ScraperService/HealthCheck"
)

// ScraperServiceClient is the client API for ScraperService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 抓取服务
type ScraperServiceClient interface {
	// 抓取单个文章
	FetchArticle(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error)
	// 批量抓取
	FetchArticles(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FetchRequest, FetchResponse], error)
	// 原始抓取（不经过 Readability 处理）
	FetchRaw(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchRawResponse, error)
	// 健康检查
	HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error)
}

type scraperServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewScraperServiceClient(cc grpc.ClientConnInterface) ScraperServiceClient {
	return &scraperServiceClient{cc}
}

func (c *scraperServiceClient) FetchArticle(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchResponse)
	err := c.cc.Invoke(ctx, ScraperService_FetchArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scraperServiceClient) FetchArticles(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FetchRequest, FetchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ScraperService_ServiceDesc.Streams[0], ScraperService_FetchArticles_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FetchRequest, FetchResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ScraperService_FetchArticlesClient = grpc.BidiStreamingClient[FetchRequest, FetchResponse]

func (c *scraperServiceClient) FetchRaw(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchRawResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchRawResponse)
	err := c.cc.Invoke(ctx, ScraperService_FetchRaw_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scraperServiceClient) HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, ScraperService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScraperServiceServer is the server API for ScraperService service.
// All implementations must embed UnimplementedScraperServiceServer
// for forward compatibility.
//
// 抓取服务
type ScraperServiceServer interface {
	// 抓取单个文章
	FetchArticle(context.Context, *FetchRequest) (*FetchResponse, error)
	// 批量抓取
	FetchArticles(grpc.BidiStreamingServer[FetchRequest, FetchResponse]) error
	// 原始抓取（不经过 Readability 处理）
	FetchRaw(context.Context, *FetchRequest) (*FetchRawResponse, error)
	// 健康检查
	HealthCheck(context.Context, *Empty) (*HealthResponse, error)
	mustEmbedUnimplementedScraperServiceServer()
}

// UnimplementedScraperServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScraperServiceServer struct{}

func (UnimplementedScraperServiceServer) FetchArticle(context.Context, *FetchRequest) (*FetchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchArticle not implemented")
}
func (UnimplementedScraperServiceServer) FetchArticles(grpc.BidiStreamingServer[FetchRequest, FetchResponse]) error {
	return status.Error(codes.Unimplemented, "method FetchArticles not implemented")
}
func (UnimplementedScraperServiceServer) FetchRaw(context.Context, *FetchRequest) (*FetchRawResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchRaw not implemented")
}
func (UnimplementedScraperServiceServer) HealthCheck(context.Context, *Empty) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedScraperServiceServer) mustEmbedUnimplementedScraperServiceServer() {}
func (UnimplementedScraperServiceServer) testEmbeddedByValue()                        {}

// UnsafeScraperServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScraperServiceServer will
// result in compilation errors.
type UnsafeScraperServiceServer interface {
	mustEmbedUnimplementedScraperServiceServer()
}

func RegisterScraperServiceServer(s grpc.ServiceRegistrar, srv ScraperServiceServer) {
	// If the following call panics, it indicates UnimplementedScraperServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScraperService_ServiceDesc, srv)
}

func _ScraperService_FetchArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScraperServiceServer).FetchArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScraperService_FetchArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScraperServiceServer).FetchArticle(ctx, req.(*FetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScraperService_FetchArticles_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ScraperServiceServer).FetchArticles(&grpc.GenericServerStream[FetchRequest, FetchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ScraperService_FetchArticlesServer = grpc.BidiStreamingServer[FetchRequest, FetchResponse]

func _ScraperService_FetchRaw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScraperServiceServer).FetchRaw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScraperService_FetchRaw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScraperServiceServer).FetchRaw(ctx, req.(*FetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScraperService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScraperServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScraperService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScraperServiceServer).HealthCheck(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ScraperService_ServiceDesc is the grpc.ServiceDesc for ScraperService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScraperService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scraper.ScraperService",
	HandlerType: (*ScraperServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchArticle",
			Handler:    _ScraperService_FetchArticle_Handler,
		},
		{
			MethodName: "FetchRaw",
			Handler:    _ScraperService_FetchRaw_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _ScraperService_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FetchArticles",
			Handler:       _ScraperService_FetchArticles_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/scraper.proto",
}
